
// Scala program to illustrate 
// the if-else-if ladder 
object ScalaIfElseIfLadder { 
	
// Main Method	 
def main(args: Array[String]) : Unit = { 
	
	// Taking a variable 
	var value: Int = 50

	if (value == 20) 
	{ 

		// print "value is 20" when 
		// above condition is true 
		println("Value is 20") 
	} 
	
	else if (value == 25) 
	{ 

		// print "value is 25" when 
		// above condition is true 
		println("Value is 25") 
	} 
	
	else if (value == 40) 
	{ 
	
		// print "value is 40" when 
		// above condition is true 
		println("Value is 40") 

	} 
	
	else
	{ 
		
		// print "No Match Found" 
		// when all condition is false 
		println("No Match Found") 
	} 
} 
} 
